### ISSUE TITLE
Attribute data strings with escape characters

### ISSUE THREAD

**Issue by prasannavl** [nfl/react-helmet#100]
With `meta` tag as 
```javascript
{ "name": "description", "content": "My 'quoted' string" },
```

This ends up with the single quotes getting replaced with `&#x27;`
Nothing including the `String.fromCodePoint` and escaping works. 

Is there any way to escape this? Considering quotes can be in a lot of places in the `meta` tag, like the above example with `description`.

**Comment by potench** [comment]
Is your concern SEO? Since it's common practice to escape double-quotes, indexing engines should interpret all the entity codes successfully. So this shouldn't be a problem for SEO. 

Is there a potential case where a browser might change `<meta name="description" content="My 'quoted' string">` to `<meta name='description' content='My 'quoted' string'>` I have seen browsers render changes like this with double-quotes before but never single quotes.

**Comment by potench** [comment]
I'm going to mark this as `wont fix`. Can you let me know what problem it's causing you so we can evaluate removing single-quotes from the entity conversion list?

**Comment by prasannavl** [comment]
Hi, sorry for the late reply. However, just as I looked into it, I realized this is actually a react issue. So, even if you were look into it, I don't think React-Helmet could do much without complex trickery and using `dangerouslySetInnerHTML` in the end, which probably wouldn't be worth it anyway. So, I'm closing this. :)

PS: I was dealing with a scenario where I had to send in data in the meta tag, which had single quotes, however I ended up dangerously setting the entire data set in the end.
