### ISSUE TITLE
[question] react-helmet work fine for seo ?

### ISSUE THREAD

**Issue by lyquocnam** [nfl/react-helmet#123]
sorry, i'm new here.
this package is good for seo ?

**Comment by potench** [comment]
Please use the Issues to report problems and request features. This question is better suited for [Stackoverflow](http://stackoverflow.com/search?q=react-helmet) 

As with any React component, you need to render `<Helmet/>` server side in order to manage your page's metadata and make that data available for search engines.

**Comment by thekris121** [comment]
@potench actually Google reads client side rendering of <Helmet/> just fine. Other search engines don't.

**Comment by santimendoza** [comment]
@kjonsson Do you have any "Prove"? Like an experiment or something? I am searching but hadn't find anything. And obviously, before we are allowed to use a componenet, we need some "proves" or "research" about it works.
