### ISSUE TITLE
is meta tags supported for client side ?

### ISSUE THREAD

**Issue by kandros** [nfl/react-helmet#130]
I'm unable to get anything but Titles to work. 

```
        <Helmet
          title="my-title"
          meta={[
            { name: 'description', content: 'super-uber application' }
          ]} />
```

Callback shows the meta but aren't rendered in the source page
![schermata 2016-04-12 alle 10 43 29](https://cloud.githubusercontent.com/assets/4562878/14455600/95d139cc-00a0-11e6-85dc-9dc07158d8ea.png)

Any idea? 

Thanks

**Comment by cwelch5** [comment]
Helmet tag looks correct.  Although, based on your screenshot, you do have meta tags, including a meta description tag.  Perhaps you are not on the route that renders `super-uber application` tag, or you are on a child route where `Helmet application` description tag has overwritten the tag from the parent (in this case, it is as designed, in order to avoid conflicts in same-named tags).

**Comment by kandros** [comment]
my bad, it was a silly mistake, not noticing it were appended below a ton of webpack styles tag and not beside other meta tags
