### ISSUE TITLE
Rendering to null causes problems with react >= 15

### ISSUE THREAD

**Issue by pierreavizou** [nfl/react-helmet#132]
React Helmet renders its PlainComponent to null, which works fine with react <= 0.14, as react renders it as a `<noscript>` tag. 
However, starting with react 15.0, returning null now renders as HTML comments, which causes an error on the client side : *Error: Unable to find element with ID X* where X is the ID number react expects to find in the DOM. 

This happens because react 15 ditches complex `data-reactid` attributes in favor of simple incremental IDs. Because there is no DOM node rendered for React Helmet, the ID numbers go from X-1 to X+1, thus causing an error because of missing #X ID. 

A simple fix would be to explicitly render as a `<noscript>` tag or any other empy HTML tag. 
I'm OK to submit a PR if this is the accepted fix.

**Comment by cwelch5** [comment]
Thanks @pierreavizou for your interest in Helmet and finding this issue with React 15. And yes, that would be a suitable fix, rendering noscript tag. Please submit.

**Comment by cwelch5** [comment]
@pierreavizou I tried to reproduce this issue, but seems to render fine.  I get a comment node - `<!-- react-empty: 25 -->` and no JS errors.  Can you elaborate on how you produced this error?

**Comment by pierreavizou** [comment]
Indeed @cwelch5 thanks for pointing that out. Your comment made me investigate further and actually the issue was caused by a too aggressive HTML minifier that would strip react comments too. 
Sorry for reporting this as an issue. 

It seems like it can be closed now as it does not really lie on React Helmet's side.

**Comment by cwelch5** [comment]
Closes #134

**Comment by alexmcmillan** [comment]
Do these comments have any negative side effects?  Performance issues?

I am rendering thousands of objects onto a map.  These are drawn onto a canvas (and hence not in the DOM) but I am using React components for them because it makes my entire application consistent.  (It's components, all the way down..)  Also, because I'm drawing to a `canvas` and not the DOM, I expected it would be performant.

These components all return `null` from `render()` and instead utilise other React lifecycle methods (eg `componentDidMount` to instantiate the API object and initially draw it onto the parent `canvas`.

This, however, causes my container `div` to hold 1 canvas and thousands of `<!-- react-empty: nnnn -->` comments.  IIUC, adding/removing *anything* from the DOM is expensive.. and these comments make me think perhaps my logic is flawed.

Is there any way to tap into the React lifecycle without touching the DOM (other than to perhaps retrieve a `canvas`) ?

**Comment by paulkamer** [comment]
@pierreavizou thanks for this hint. I had the same issue. I also needed to disable html minification at Cloudflare too.
