### ISSUE TITLE
Override tags already in the DOM

### ISSUE THREAD

**Issue by nsimonson** [nfl/react-helmet#143]
Is it possible to override tags client side that already exist in the html? Similar to how the title tag get's rewritten. I know rendering server side is the ideal solution, but save that. I'm currently ending up with two meta description tags. One from the html and one managed by Helmet.

**Comment by cwelch5** [comment]
@nsimonson Thanks for your interest in Helmet.  No, currently, it's not possible to override tags not managed in Helmet.  This was done on purpose in case users wanted/needed to manage tags outside of Helmet.  You should have the flexibility to make sure Helmet doesn't duplicate any current tags you have.

**Comment by nsimonson** [comment]
@cwelch5 Thanks for the insight. Once we move to server side rendering it shouldn't be a problem. However I am having issues with my ld+json script tag not being overwritten by a nested component.

**Comment by mmahalwy** [comment]
@nsimonson i am having problem with not overriding too..

**Comment by cwelch5** [comment]
@nsimonson Scripts act a little differently from meta/link tags.  You can't overwrite tags because the src or innerHTML will always be unique.  Currently, if you don't want a script to show up in a nested component, move it to another part of the route tree.  Keep in mind if you have it at the root of your app, every component will have that script.

Perhaps @nsimonson @mmahalwy, you can provide some info about your use case so I can help you solve it faster.

**Comment by mmahalwy** [comment]
@cwelch5 actually, I found what my problem was... it's really silly but too a while to uncover. 
```
{name: 'twitter:description', '...'} !== {property: 'twitter:description', '...'}
```
