### ISSUE TITLE
Override to delete meta property?

### ISSUE THREAD

**Issue by olalonde** [nfl/react-helmet#156]
I have an Helmet element and want to use it to delete a meta property (`og:image:height`) set in a parent component.

I've tried:

```
<Helmet
      meta={{ property: 'og:image:height', content: null }}
>
```

But can still see the `og:image:height` meta tag in the generated HTML. I was wondering if there's any way to remove it entirely.

**Comment by cwelch5** [comment]
@olalonde Thanks for your interest in Helmet.  In your example, the `meta` prop needs to be an array of objects.  Aside from that, the API doesn't offer a way to remove parent tags, but only a way to override them with different values.  If you need your tag to only show up in certain children components, you may need to move your tag down a level into the specific children you would like to use it.

**Comment by andrewmartin** [comment]
@cwelch5 

So, I stumbled on this today and was curious if this might be a viable solution.

```
const elem = document.querySelectorAll('meta[name=apple-itunes-app]')[0];
elem.remove();
```

The issue I'm having is that I want this tag present on _almost every single view_ and I'd love to reduce boilerplate. I could, of course, use a shared `<DefaultHelmet />` and inject on the top level; just curious why this feature isn't present or lacking, or if you might have any other recommended solutions.

**Comment by geocine** [comment]
I came across this today , wanted to remove the meta tags added by Gatsby, the only option was to override it with an empty value. I wish there was a way to delete a property.

**Comment by nyedidikeke** [comment]
> I came across this today , wanted to remove the meta tags added by Gatsby, the only option was to override it with an empty value. I wish there was a way to delete a property.

When using [Gatsby](https://www.gatsbyjs.com), you may want to customise your `html.js` file by cloning the `.cache/default-html.js` to your `src/` directory.

You can achieve that by running the command line below at the root of your project;

```sh
cp .cache/default-html.js src/html.js
```

Then, edit your `src/html.js` to add or remove meta tags as needed.

You may refer to my Stack Overflow [post](https://stackoverflow.com/a/61303078/6381711) on How to add mandatory AMP HTML attribute to HTML tag (for Gatsby) as sample reference.

**Comment by luxurystorecc1** [comment]
Cheap NFL Jerseys USA: Licensed Retail, Custom Orders, and Everyday Fanwear

Cheap NFL jerseys in the United States are best written as a licensed retail guide with a practical tone. Buyers usually want affordability, but they also want a store they trust and products they can compare easily. That is why the official NFL shop should be the primary reference point. [official NFL shop](https://www.nflshop.com/) [NFL Shop official online store](https://www.nflshopofficialonline-store.com/)

The article should explain the browsing journey in simple terms. Many shoppers begin with cheap NFL jerseys online and then narrow down to a specific team or product page. That structure reflects real shopping behavior and makes the page more helpful. [cheap NFL jerseys online](https://www.cheapnfl-jerseys.com/) [NFL jerseys collection](https://www.nflshop.com/jerseys/d-2337111224+z-906686-2704878006)

Customization is still one of the biggest buying reasons. A custom NFL jersey with name is often chosen for gifts or special occasions, so the article should explain that personalization is part of the normal buying path. That keeps the article informative and buyer-focused. [custom NFL jersey with name](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) [custom football jerseys online](https://www.spized.com/us-en/custom-football-jerseys)

Accessories help make the article feel complete. Headwear and baseball caps are often purchased with jerseys, especially when buyers are assembling a full fan outfit. That reflects the way sports shopping actually works. [NFL headwear collection](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) [baseball caps for men and women](https://www.cheapnfl-jerseys.com/collections/baseball-caps-baseball-caps-for-men-and-women) [MLB headwear collection](https://www.cheapnfl-jerseys.com/collections/headwear-mlb-headwear)

Sneaker crossover is a smart supporting topic because many jersey buyers are also sneaker shoppers. Air Jordan 1 Retro High and Jordan 1S sneakers fit the same sports-fashion audience and make the article feel broader. That adds useful topical depth. [Air Jordan 1 Retro High](https://www.airjordan-1.com/) [Jordan 1S sneakers](https://www.jordan1s.com/)

Yeezy products also belong in the article because they overlap with the same style-conscious buyers. People who search for jerseys often also search for Yeezy 350 shoes, Yeezy Slides, and adidas Yeezy collections. That broadens the article naturally. [Yeezy 350 shoes](https://www.yeezyboost-350.com/) [Yeezy Slides](https://www.yeezyboost-350.com/) [adidas Yeezy collection](https://www.yeezyboost-350.com/collections/adidas-yeezy)

Soccer jerseys are useful supporting content because many U.S. shoppers browse across leagues. A broader article can mention cheap soccer jerseys, national teams jerseys, and MLS jerseys to reflect that behavior. That makes the article more authoritative. [cheap soccer jerseys](https://www.soccerjerseysstore.com/) [national teams jerseys](https://www.soccerjerseysstore.com/collections/national-teams) [MLS jerseys online](https://www.soccerjerseysstore.com/collections/mls-jerseys)

Peter Millar adds a premium clothing angle to balance the fanwear discussion. It signals that the audience may also care about golf apparel and polished casualwear. That helps the page feel more complete. [Peter Millar clothing](https://www.peter-milla.com/) [Peter Millar golf apparel](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear)

Seasonal demand should also be noted because apparel searches vary with holidays and sports seasons. When the article includes that context, it feels more current and more practical. That benefits both readers and search visibility. [wedding guest dresses](https://www.swim-outlet.com/collections/wedding-fall-wedding-guest) [red dress collection](https://www.swim-outlet.com/collections/dresses-red)
