### ISSUE TITLE
What about concurrency?

### ISSUE THREAD

**Issue by halt-hammerzeit** [nfl/react-helmet#240]
You're saying that `Helment.rewind()` does the trick on the server side.
What about concurrency? ("thread safe ty")
If two React renders happen at the same time will `Helment.rewind()` mess it all up.
I guess it will.
If that's so you should clearly state it in the readme.

**Comment by halt-hammerzeit** [comment]
Ok, this library is confirmed to be not thread safe.
https://github.com/gaearon/react-document-title/issues/7

**Comment by catamphetamine** [comment]
For anyone coming from Google, I refactored `react-helmet` with my own `@meta()` decorator for setting `<title/>` and `<meta/>` tags:
https://github.com/catamphetamine/react-isomorphic-render/blob/master/source/meta.js

The approach used is:
* only `<Route/>`s can define `<title/>` and `<meta/>` tags
* they can do it only in this decorator
* the decorator can take data from Redux state for the tags
* when `react-router` matching finishes it yields a chain of `components` which are then searched for `@meta()`, the found `@meta()` is merged and the result is diffed with the current contents of `<head/>` to then update changed tags, remove no longer existent tags and add new tags

It works in asynchronous environment because doesn't use `react-side-effect` (which `react-helmet` does) and therefore doesn't rely on global variables.
Therefore it's React 16 ready and works with streamed server-side rendering.
