### ISSUE TITLE
how to make meta tags on the fly in the client

### ISSUE THREAD

**Issue by cyrfer** [nfl/react-helmet#262]
Why does this work?
```
return (
    <Helmet>
        <title>{page.title}</title>
        <meta name="description" content="stuff" />
    </Helmet>
);
```

But this does not work?
```
const Meta = (props) => (
    <meta name={props.name} content={props.content} />
);

...other component...
const moreMeta = [{name:"description", content:"stuff"}].map((m, idx) => {
return (
        <Meta key={idx} name={m.name} content={m.content} />
    );
});

return (
    <Helmet>
        <title>{page.title}</title>
        {moreMeta}
    </Helmet>
);
```
Here the question on SO:
http://stackoverflow.com/questions/43166488/data-driven-meta-tags-with-react-helmet-in-client

**Comment by doctyper** [comment]
@cyrfer Your use-case does not work is because you're passing a capital-M `<Meta />` component into Helmet. In other words, it's a custom component. Helmet only looks for valid head tags (i.e. lowercase-m `<meta />`) and ignores / warns on any other component it comes across.

The reason Helmet does this check is that it does not actually allow React to _render_ tags passed into Helmet. If we did, you would have invalid markup since head tags would be written into your body. Instead it collects these tags before they can be rendered, and uses their values to write to your document head. It discards any component that is not a valid head tag.

We currently only perform a shallow check for tags. Your valid `meta` tag is deeply nested inside of your `<Meta />` component, which is why your tags are being missed. This however would work (note the lowecase `m`):

```js
const moreMeta = [{
    name: "description",
    content: "stuff"
}].map((m, idx) => {
    return (
        <meta key={idx} name={m.name} content={m.content} />
    );
});

return (
    <Helmet>
        <title>{page.title}</title>
        {moreMeta}
    </Helmet>
);
```

**Comment by mvasin** [comment]
I'm trying to use [GoogleFont](https://github.com/KyleAMathews/typography.js#reactjs-helper-components) component that generates `<link ... />`.

Placing `<GoogleFont>` in `<Helmet>` doesn't work for the reasons stated above, so I tried to render the `<GoogleFont>` to string with `ReactDOMServer` and use the string as `<Helmet>` children, but it also doesn't work because it's escaped. @doctyper Is there a workaround for this case?

Relates to KyleAMathews/typography.js/issues/177
