### ISSUE TITLE
Feature Request: Append content to body tag attributes via Helmet

### ISSUE THREAD

**Issue by jeffredodd** [nfl/react-helmet#365]
When using react Helmet, I would like a way to append content into my attributes onto my `<body>` tag.

For example this code will set my body class ...
**JSX**
```
<Helmet>
  <body class='first-class' />
</Helmet>
```

**Output**
`<body class='first-class'>`

And when I have a component deeper in my application call helmet like such the body class is overwritten...

**JSX**
```
<Helmet>
  <body class='second-class' />
</Helmet>
```

**Output**
`<body class='second-class'>`

**Desired Output**
`<body class='first-class second-class'>`

Currently the fix for this in my application is to call the following which is not sustainable as we now have to maintain many body classes throughout our application...
**JSX**
```
<Helmet>
  <body class='first-class second-class' />
</Helmet>
``` 

**_Potential Solution_**
In order to set this up correctly you cannot call class but maybe using something like the following would be an appropriate way to append an item to helmet as calling class directly should still overwrite class so that a breaking change is not introduced to helmet? 

**JSX**
```
<Helmet>
  <body append-class='second-class' />
</Helmet>
```

**Comment by andrewb273** [comment]
Isn't this creeping beyond the scope of react-helmet? Helmet i.e. head?

**Comment by sneridagh** [comment]
+1

**Comment by panzerdp** [comment]
While react-helmet does not support appending classes, you can simply add new attributes to your body tag. Then use those attributes as selectors.

E.g.:
```jsx
<App>
  <Helmet>
    <body data-first="true" />
  </Helmet>
  <Helmet>
    <body data-second="true" />
  </Helmet>
</App>
```
The output will be:
```html
<body data-first="true" data-second="true" />
```

Then use attribute selectors:
```css
body[data-first] {
  color: blue;
}

body[data-second] {
  color: red;
}
```

**Comment by tmbtech** [comment]
> We have a 3rd party script adding classes to the body tag, but Helmet is overwriting them . Why is appending classes not supported?

The typical and recommended approach is to not wrap the entire body but to use helmet as a sibling to the body. 

ie 
```   
<div className="application">
    <Helmet>
        <meta charSet="utf-8" />
    </Helmet>
    <body>.....</body>
</div>
```
https://github.com/nfl/react-helmet#as-react-components

I could be misunderstanding the issue, let me know if that helps.

**Comment by Noyabronok** [comment]
@tmbtech We're using react strictly client side, and Helmet to add some data attributes and update className='...' to an existing body tag.
If I understand correctly, your example applies to server side render, which is a different use case.

**Comment by tmbtech** [comment]
@Noyabronok can you provide an example via https://codesandbox.io

**Comment by bittu** [comment]
bump!!!
@Noyabronok example please.
@jeffredodd @tmbtech were you able to achieve this?

**Comment by jeffredodd** [comment]
This task was for a former project but I heard they made quite a bit of progress with this in our UI platform by using https://github.com/staylor/react-helmet-async .

**Comment by bittu** [comment]
@jeffredodd Ah ok... [https://github.com/staylor/react-helmet-async](https://github.com/staylor/react-helmet-async) is this package for SSR only or client-side rendering as well?

**Comment by javierguzman** [comment]
Hello all, I am looking for placing a noscript snippet within body. Is there a way to achieve this with react-helmet? Thank you in advance

**Comment by IPRIT** [comment]
Any updates? Still actual.

**Comment by jeffredodd** [comment]
Closing as React has changed a ton in 4 years and this is not a good proposed solution. Plus this repo hasn't received updates in a while.

**Comment by luxurystorecc1** [comment]
Cheap NFL Jerseys Europe: Licensed Retail, Fanwear Trust, and Category Depth

Cheap NFL jerseys in Europe should be written with local trust and official retail in mind. European buyers often care about whether the seller feels legitimate and whether shipping is clearly explained. That makes the regional official shop the strongest starting point. [NFL Shop Europe official](https://europe.nflshop.com/en/) [official NFL shop](https://www.nflshop.com/)

A useful article should explain the browsing flow clearly. Many readers begin with cheap NFL jerseys online and then move into a collection page to compare styles and teams. That mirrors how real shoppers browse and makes the article more intuitive. [cheap NFL jerseys online](https://www.cheapnfl-jerseys.com/) [NFL jerseys collection](https://www.nflshop.com/jerseys/d-2337111224+z-906686-2704878006)

Customization remains valuable because many buyers want personalized products. A custom football jerseys online page gives readers a clearer idea of what options exist before they buy. That makes the article more practical and more useful. [custom football jerseys online](https://www.spized.com/us-en/custom-football-jerseys) [custom football shirts delivery](https://www.tdsportswear.com/custom-football-jerseys/)

Accessories belong in the same article because they help create a complete fanwear order. Caps and headwear are common add-ons that make the shopping basket feel more complete. That gives the content more realistic depth. [NFL headwear collection](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) [baseball caps for men and women](https://www.cheapnfl-jerseys.com/collections/baseball-caps-baseball-caps-for-men-and-women)

Sneaker crossover is highly relevant in Europe. Air Jordan 1 Retro High and Jordans 1 shoes fit the same sports-fashion audience as jersey buyers and help broaden the article naturally. That improves topical relevance. [Air Jordan 1 Retro High](https://www.airjordan-1.com/) [Jordans 1 shoes](https://www.jordan1s.com/)

Yeezy terms should also be included because they reflect the same style behavior. Buyers who search for jerseys often also search for Yeezy 350 shoes, Yeezy Slides, and adidas Yeezy collections when building a casual outfit. That adds useful breadth. [Yeezy 350 shoes](https://www.yeezyboost-350.com/) [Yeezy Slides](https://www.yeezyboost-350.com/) [adidas Yeezy collection](https://www.yeezyboost-350.com/collections/adidas-yeezy)

Soccer jerseys are especially important in Europe because football is the dominant sport. A broader article can mention cheap soccer jerseys, national teams jerseys, and Spain national teams jerseys to match regional demand. That strengthens the GEO angle. [cheap soccer jerseys](https://www.soccerjerseysstore.com/) [national teams jerseys](https://www.soccerjerseysstore.com/collections/national-teams) [Spain national teams jerseys](https://www.soccerjerseysstore.com/collections/national-teams-europe-spain)

Peter Millar adds a premium clothing contrast that helps balance the topic. It shows that the same audience may also care about golf apparel and polished casualwear. That makes the article feel more complete. [Peter Millar clothing](https://www.peter-milla.com/) [Peter Millar golf apparel](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear)

Seasonal demand should also be mentioned because apparel searches shift during holidays and sports seasons. When the article reflects that reality, it feels more current and practical. That supports search performance too. [wedding guest dresses](https://www.swim-outlet.com/collections/wedding-fall-wedding-guest) [red dress collection](https://www.swim-outlet.com/collections/dresses-red)
