### ISSUE TITLE
SSR async title?

### ISSUE THREAD

**Issue by nikola1970** [nfl/react-helmet#382]
Hello guys, having problems with Helmet and SSR.

My SSR works well for async actions and generating prerendered html with no problems but the problem is async data which I am getting via props and rendering in component in:
<Helmet> <title>{DYNAMIC_VALUE_FROM_Async_props} </title></Helmet> (Markup not showing Helmet wrapper tag)

Is not rendered, just a blank. How could I wait on props to come and then get prerendered title as well? It works in client, title is updating, but not on inital load and ssr.

Thanks!

**Comment by AubreyHewes** [comment]
"My SSR works well for async actions and generating prerendered html with no problems " 

"but the problem is async data"

"works in client, title is updating, but not on inital load and ssr."

So SSR/initial load is not working as you expect? Which static framework are you using, if any?

SSR requires data for rendering. This ensures your title is fulfilled. If not doing this and your app is requesting the title async/after SSR then yes your title will be empty.

Without more information and a working example of your problem it is hard to give an answer.
