### ISSUE TITLE
Create Migration Guide 5.x => 6.x

### ISSUE THREAD

**Issue by tmbtech** [nfl/react-helmet#423]
- [ ] Create Migration Guide
- [ ] Look into creating a code-mod for easier upgrades.

**Comment by catamphetamine** [comment]
So, given the still empty changelog for `6.0.0` seems that no one really has an idea what happens in this repo anymore.

![image](https://user-images.githubusercontent.com/477167/50539016-70f4e200-0b8a-11e9-8b78-4a03c04e7f4a.png)

And apparently the maintainers don't know how to use branches and they don't know how to release fixes in a branch.
Particularly, this issue is still not resolved in 5.x and no one cares https://github.com/nfl/react-helmet/issues/373.
Looks like the maintainers are really sub-average and unprofessional developers.
