### ISSUE TITLE
Note to maintainers

### ISSUE THREAD

**Issue by sneridagh** [nfl/react-helmet#490]
Folks, the community needs this to be merged AND released:
https://github.com/nfl/react-helmet/pull/472

that easy as a dependency update. I see the implications, and that might be done in a breaking major release. Then do it, or update the 6.0.0beta that is one year old (I guess stale because of something).

and most probably it will need this to make travis work again.:
https://github.com/nfl/react-helmet/pull/473

If you can't maintain the project anymore, try to find someone who can. I guess there will be plenty of volunteers.

**Comment by Remzi1993** [comment]
@sneridagh I think everybody is going to switch  over to React Helmet Async > https://github.com/staylor/react-helmet-async because this annoys me. The project is not actively maintained anymore.

**Comment by hencatsmith** [comment]
@Remzi1993 thank you for posting that link! Been struggling with unresolved `react-helmet` issues for a while and had no idea there was already a fork available that had gained a bunch of traction! I've immediately begun the process of migrating my employer's site over! Thank you thank you thank you! ❤️

Taking a second look here I notice there hasn't been anything merged to `react-helmet` since May. I wonder if somebody senior in the NFL engineering team might see an opportunity to do some much-needed leadership work here and archive this project with a prominent link to `react-helmet-async` in the README.

**Comment by Remzi1993** [comment]
@hencatsmith You're welcome 😉
I also found out a couple of days ago. I was searching the internet and I stumbled upon this by accident.

**Comment by cwelch5** [comment]
Thanks for everyone's patience. We are actively working on 6.0.0 release. 6.0.0-beta.2 is available and will work with the latest React version.
