### ISSUE TITLE
Meta tags not rendered

### ISSUE THREAD

**Issue by kib357** [nfl/react-helmet#51]
Constant TAG_PROPERTIES doesn't contain "CONTENT", and this example:
meta={[
                        {"name": "description", "content": "Helmet application"},
                        {"property": "og:type", "content": "article"}
                    ]}
not render anything.

**Comment by cwelch5** [comment]
That is okay that TAG_PROPERTIES doesn't contain "CONTENT" - those properties identify attributes that become the primary key for that tag, which is relevant when comparing tags to other tags.  "CONTENT" is not a primary key because you can have duplicate content between tags, and they won't override each other.  But if you have two tags both with PROPERTY of "og:type", then they will override or compose according to the examples.

With regards to that particular example, is it a problem with prerendering on the server?  or is it not showing up on the client as well?
