### ISSUE TITLE
Help url 

### ISSUE THREAD

**Issue by liviocmachado** [nfl/react-helmet#608]
You can help me, how can I make it work:

My env:
REACT_APP_ASSETS='https://mypage.s3.amazonaws.com/assets/'
```

<Helmet>
    <link rel="stylesheet" href="{process.env.REACT_APP_ASSETS}css/pages/login/login-1.css?v=7.0.4"/>
</Helmet>

```

**Comment by omrprks** [comment]
Hey @liviocmachado , the code snippet you provided probably doesn't work because 'process.env.REACT_APP_ASSETS' in the href isn't being evaluated. You need to use a template literal (backticks), so try the following:

```
<Helmet>
    <link rel="stylesheet" href={`${process.env.REACT_APP_ASSETS}css/pages/login/login-1.css?v=7.0.4`} />
</Helmet>
```

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
