### ISSUE TITLE
Googlebot does not crawl React Helmet meta description

### ISSUE THREAD

**Issue by shacco** [nfl/react-helmet#612]
In fact google does not recognize it neither

**Comment by alayo** [comment]
Same

**Comment by marybeshaw** [comment]
Head tags need to be pre-rendered in order for them to be recognized by bots.  Take a look at this: https://prerender.io/

**Comment by creativesuraj** [comment]
Googlebot will not be able to scrape meta descriptions set by React helmet because `react-helmet` sets meta description on the client side, which requires a Javascript engine but bots don't contain Javascript engine. You might consider static site generators or server side rendering using [Gatsby](https://github.com/gatsbyjs/gatsby) or [Next](https://github.com/vercel/next.js).

**Comment by meness** [comment]
@creativesuraj Google understands JS perfectly, but sometimes it doesn't see changes. I think it's Helmet. A workaround is using Server Side Rendering.

**Comment by corneliugaina** [comment]
In fact, its a while that Google doesn't apprehend all the <meta> tags in the code (since Panda update in 2009 ? ), take a look to the short video in the link below (~2min) where the guy explains what and why of this. 
https://support.google.com/webmasters/answer/79812?hl=en 

You also have a exhaustive list of meta's that google crawler see.

**Comment by idbd1** [comment]
is this still an issue? I want to have dynamic meta tags and was wondering if the google bot will wait until the new ones are loaded.
