### ISSUE TITLE
Is this project actively maintained????

### ISSUE THREAD

**Issue by matt-whitaker** [nfl/react-helmet#613]
Is this project actively maintained? Are you offering suggested alternatives? Seems like this project has gone dead with some nasty bugs left in it. 

https://github.com/nfl/react-helmet/pull/400 been open for two years and that's just ridiculous for something so trivial. How do we get this merged?

**Comment by matt-whitaker** [comment]
nvm, i'm just gonna bug someone directly to get this complete.

**Comment by richardscarrott** [comment]
@matt-whitaker did you find out if this project is maintained? I think it would be be responsible for the original maintainers to put up a notice on the README pointing to react-helmet-async or other alternatives; I'm especially concerned because of this security bug https://github.com/nfl/react-helmet/pull/614
