### ISSUE TITLE
Gatsby - Facebook SEO can't get result on Production Link but in Stagging it works

### ISSUE THREAD

**Issue by irwansyafani** [nfl/react-helmet#653]
I having an issue that [Facebook Developer](https://developers.facebook.com/tools/debug/) can't get the result for SEO on Production Link
but, in Stagging Link it works correctly

have you guys faced an issue like this?

**Comment by Elius94** [comment]
I think it's because this react plugin changes the index.html only if js is enabled... I suppose that the social engines that generates the preview reads only the "crude" index.js generated in the build process.

To bypass this trouble i've created this usefull npx command:

https://github.com/Elius94/js-seo-ingector

Enjoy

**Comment by irwansyafani** [comment]
okay, i'll try it later @Elius94
